ALTER TABLE assistants ADD COLUMN template_id TEXT NOT NULL DEFAULT '';
ALTER TABLE assistants ADD COLUMN tagline TEXT NOT NULL DEFAULT '';
ALTER TABLE assistants ADD COLUMN best_for TEXT NOT NULL DEFAULT '';
ALTER TABLE assistants ADD COLUMN not_for TEXT NOT NULL DEFAULT '';
ALTER TABLE assistants ADD COLUMN suggested_model TEXT NOT NULL DEFAULT '';
